---
- name: this playbook is used to start service only when httpd is installed on servers under webservers group
  hosts: webservers
  become: true
  tasks:
  - name: install package
    yum:
      name: httpd
      state: installed
    notify: start httpd service
  handlers:
  - name: start httpd service
    service:
      name: httpd
      state: started
