---
- name: this playbook is used to install httpd/apache2 and run httpd/apache2 on group of servers/target system/managed node based on there os_family
  hosts: all
  become: true
  vars:
    port: 8080
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    notify: start httpd service
  
  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    notify: start apache2 service

  - name: copy index.html file to all managed nodes
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666

  - name: Ensure the default Apache port is {{ port }}
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: Listen {{ port }}
    when: ansible_os_family == "RedHat"
    notify: restart apache

  - name: Ensure the default Apache port is {{ port }} on ubuntu
    lineinfile:
      path: /etc/apache2/ports.conf
      regexp: '^Listen '
      insertafter: "# /etc/apache2/sites-enabled/000-default.conf"
      line: Listen {{ port }}
    when: ansible_os_family == "Debian"
    notify: restart apache2
  
  handlers:
  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: start apache2 service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: restart apache
    service:
      name: httpd
      state: restarted

  - name: restart apache2
    service:
      name: apache2
      state: restarted
