---
- name: setup tomcat
  hosts: all
  become: true
  tasks:
  - name: install java
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"
  - name: install java ubuntu
    #default jdk
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"
  - name: download tomcat packages
    get_url:
      url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.102/bin/apache-tomcat-9.0.102.tar.gz
      dest: /opt
  - name: untar tomcat package
    unarchive:
      src: /opt/apache-tomcat-9.0.102.tar.gz
      dest: /opt
      remote_src: yes
  - name: add execution permission on startup.sh file
    file:
      path: /opt/apache-tomcat-9.0.102/bin/startup.sh
      mode: 0777
  - name: start tomcat services
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-9.0.102/bin
