---
- name: this playbook will uninstall package and stop service based on operating system of amanged nodes
  #hosts: webservers
  hosts: all
  become: true
  tasks:
  - name: stop service httpd
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"
  - name: remove package httpd
    yum:
      name: httpd
      state: removed
    when: ansible_os_family == "RedHat"
  - name: stop service apache2
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"
  - name: uninstall apache2
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"
